### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by Tazeg** [alash3al/redix#32] opened 2020-03-06 18:20 UTC
I use `"predis/predis": "^1.1"` with PHP and redix as an IP rate limiter.
Today my server sent ERROR 500, but redix was still alive. So i looked at the web server error log. Here is what I got : 

```
www[5]: PHP Fatal error:
Uncaught Predis\Response\ServerException: db error: 
open redix-data/level/0/CURRENT: 
too many open files in /flex/storage/xxx/php/vendor/predis/predis/src/Client.php:370
#012
Stack trace:
#012#0
/flex/storage/xxx/php/vendor/predis/predis/src/Client.php(335): 
Predis\Client->onErrorResponse(Object(Predis\Command\KeyTimeToLive), 
Object(Predis\Response\Error))
#012#1
/flex/storage/xxx/php/vendor/predis/predis/src/Client.php(314):
Predis\Client->executeCommand(Object(Predis\Command\KeyTimeToLive))
#012#2
/flex/storage/xxx/php/myapp/class.ratelimit.redix.php(72): 
Predis\Client->__call('ttl', Array)
#012#3
/flex/storage/xxx/php/myapp/script.php(61):
RateLimit->getSleepTime($ipaddr)
#012#4
{main}
#012
thrown in /flex/storage/xxx/php/vendor/predis/predis/src/Client.php on line 370
```

To solve the issue, I stopped redix, then I did `rm -rf redix-data` and started it again.
I'm not sure about what was wrong here. If it helps.

**Comment by alash3al** [comment] 2020-03-06 18:39
based on the specified trace  `too many open files in /flex/storage/xxx/php/vendor/predis/predis/src/Client.php:370`, this means that the client itself `predis` couldn't be able to create a new connection to redix because of there are too many connections already opened, 

- Do you run redix on the same server running your php app?
- Does your app have a mid to large traffic on it?

**Comment by Tazeg** [comment] 2020-03-06 19:18
php is on one server, redix is on another. I may have 1 request every 5 seconds 24h a day.

**Comment by alash3al** [comment] 2020-03-06 19:40
we don't have more data about the issue,

in my opinion (based on the specified trace), it is coming from the client-side "the app itself" (not the server-side "redix"), I don't want to put any assumptions.

anyway, if the error occurred again, just look at redix output (stderr/stdout), if there were nothing related to any error, then you may need to debug your app server to know what is happing out there.

**Comment by alash3al** [comment] 2020-03-06 19:45
Ok, the issue is wired somehow, I don't want to put any assumptions,

redix server may be closed in a none-graceful way, so there may be a corrupted data?

**Comment by Tazeg** [comment] 2020-03-06 20:07
Yes, it may be from predis : https://github.com/nrk/predis/issues/345
Sorry for inconvenience.
Thanks.

**Closed** 2020-03-06 20:41 UTC

**Comment by Tazeg** [comment] 2020-03-27 09:06
Sorry to re-open the issue.

I had the error again `accept tcp [::]:6380: accept4: too many open files`.

I found this question/answer : https://serverfault.com/questions/48717/practical-maximum-open-file-descriptors-ulimit-n-for-a-high-volume-system

On my server `ulimit -n` gives `1024`. Do I need to increase this limit ?

The page also says : "check if your application has a memory/file descriptor leak. Use lsof to see all it has open to see if they are valid or not. Don't try to change your system to work around applications bugs."

So here is `lsof` of redix 1.10 : 

```
COMMAND     PID USER   FD      TYPE  DEVICE SIZE/OFF   NODE NAME
redix_1.1 16208 jeff  cwd       DIR   252,1     4096 529072 /home/jeff
redix_1.1 16208 jeff  rtd       DIR   252,1     4096      2 /
redix_1.1 16208 jeff  txt       REG   252,1 11117728 529135 /home/jeff/redix_1.10
redix_1.1 16208 jeff    0u      CHR   136,2      0t0      5 /dev/pts/2
redix_1.1 16208 jeff    1u      CHR   136,2      0t0      5 /dev/pts/2
redix_1.1 16208 jeff    2u      CHR   136,2      0t0      5 /dev/pts/2
redix_1.1 16208 jeff    3u     IPv6 1995123      0t0    TCP *:7090 (LISTEN)
redix_1.1 16208 jeff    4u  a_inode    0,13        0  10595 [eventpoll]
redix_1.1 16208 jeff    5u     IPv6 1995125      0t0    TCP *:6380 (LISTEN)
redix_1.1 16208 jeff    7uW     REG   252,1        0 523750 /home/jeff/redix-data/level/0/LOCK
redix_1.1 16208 jeff    8w      REG   252,1      361 523753 /home/jeff/redix-data/level/0/LOG
redix_1.1 16208 jeff    9w      REG   252,1       54 523754 /home/jeff/redix-data/level/0/MANIFEST-000000
redix_1.1 16208 jeff   10w      REG   252,1     6945 523777 /home/jeff/redix-data/level/0/000001.log
```

**Comment by alash3al** [comment] 2020-03-28 17:35
yes, you should increase the open file limits on the server that hosts redix
